"""内置 CI 属性合同。

生成器与数据质量规则共享这份字段清单，避免用户指定不存在或类型不匹配的
字段后，系统仍然声称缺陷注入成功。
"""

MIN_DEFAULT_ATTRIBUTES = 10

CI_ATTRIBUTE_KINDS: dict[str, dict[str, str]] = {
    "data_center": {
        "location": "string",
        "country": "string",
        "site_code": "string",
        "region": "string",
        "timezone": "string",
        "tier": "string",
        "floor_area_sqm": "integer",
        "power_capacity_kw": "integer",
        "cooling_type": "string",
        "status": "string",
        "environment": "string",
        "owner": "string",
    },
    "rack": {
        "asset_tag": "string",
        "room": "string",
        "row": "string",
        "u_height": "integer",
        "power_capacity_kw": "integer",
        "current_power_kw": "integer",
        "cooling_zone": "string",
        "temperature_c": "integer",
        "status": "string",
        "environment": "string",
    },
    "physical_server": {
        "hostname": "string",
        "serial_number": "string",
        "vendor": "string",
        "model": "string",
        "cpu_cores": "integer",
        "memory_gib": "integer",
        "management_ip": "string",
        "os_name": "string",
        "os_version": "string",
        "status": "string",
        "environment": "string",
    },
    "virtual_machine": {
        "hostname": "string",
        "uuid": "string",
        "cpu_cores": "integer",
        "memory_gib": "integer",
        "disk_gib": "integer",
        "ip_address": "string",
        "power_state": "string",
        "os_name": "string",
        "status": "string",
        "environment": "string",
    },
    "network_device": {
        "hostname": "string",
        "serial_number": "string",
        "vendor": "string",
        "model": "string",
        "device_role": "string",
        "port_count": "integer",
        "management_ip": "string",
        "software_version": "string",
        "status": "string",
        "environment": "string",
    },
    "ip_address": {
        "address": "string",
        "prefix_length": "integer",
        "ip_version": "integer",
        "address_type": "string",
        "allocation_type": "string",
        "dns_name": "string",
        "gateway": "string",
        "vlan_id": "integer",
        "status": "string",
        "environment": "string",
    },
    "application": {
        "code": "string",
        "owner": "string",
        "environment": "string",
        "criticality": "string",
        "lifecycle_status": "string",
        "version": "string",
        "language": "string",
        "framework": "string",
        "deployment_model": "string",
        "business_unit": "string",
    },
    "database": {
        "engine": "string",
        "version": "string",
        "host": "string",
        "port": "integer",
        "database_name": "string",
        "charset": "string",
        "storage_gib": "integer",
        "high_availability": "string",
        "environment": "string",
        "status": "string",
    },
    "middleware": {
        "type": "string",
        "version": "string",
        "host": "string",
        "port": "integer",
        "instance_name": "string",
        "protocol": "string",
        "cluster_mode": "string",
        "instance_count": "integer",
        "environment": "string",
        "status": "string",
    },
    "kubernetes_cluster": {
        "version": "string",
        "environment": "string",
        "status": "string",
        "cni": "string",
        "cluster_name": "string",
        "api_endpoint": "string",
        "pod_cidr": "string",
        "service_cidr": "string",
        "distribution": "string",
        "container_runtime": "string",
    },
    "kubernetes_node": {
        "role": "string",
        "version": "string",
        "status": "string",
        "environment": "string",
        "hostname": "string",
        "internal_ip": "string",
        "cpu_cores": "integer",
        "memory_gib": "integer",
        "disk_gib": "integer",
        "container_runtime": "string",
        "os_name": "string",
    },
    "kubernetes_workload": {
        "kind": "string",
        "namespace": "string",
        "replicas": "integer",
        "image": "string",
        "status": "string",
        "workload_name": "string",
        "uid": "string",
        "available_replicas": "integer",
        "restart_policy": "string",
        "service_account": "string",
        "environment": "string",
    },
}
