"""输入与规模上限：防止超大规格、超长文本与失控分页。"""

# 单个 CI 类型数量上限
MAX_COUNT_PER_TYPE = 20_000
# 数据集 CI 总量上限
MAX_TOTAL_CI = 30_000
# 单个规格中 CI 类型条目上限
MAX_CI_TYPE_ENTRIES = 12
# 单个规格中关系规则上限
MAX_RELATION_ENTRIES = 32

# 文本上限
MAX_NAME_LENGTH = 120
MAX_DESCRIPTION_LENGTH = 500
MAX_PROMPT_LENGTH = 4_000
MAX_QUERY_LENGTH = 200
MAX_OVERRIDE_PREFIX_LENGTH = 40

# 分页
DEFAULT_PAGE_SIZE = 100
MAX_PAGE_SIZE = 200

# AI 请求与响应
MAX_AI_PROMPT_CHARS = 4_000
MAX_AI_RESPONSE_BYTES = 256 * 1024
